import Eye from "./eye-of-nyrzeff.svg?react";
import { ChevronRight, Contact, Mail, Github, MapPin } from "lucide-react";

export const icons = {
  eye: Eye,
  chevronRight: ChevronRight,
  contact: Contact,
  mail: Mail,
  github: Github,
  mapPin: MapPin,
};

export const devicons = {
  React: "devicon-react-plain colored",
  JavaScript: "devicon-javascript-plain colored",
  TypeScript: "devicon-typescript-plain colored",
  Bash: "devicon-bash-plain",
  C: "devicon-c-plain colored",
  Python: "devicon-python-plain colored",
  Rust: "devicon-rust-plain",
  HTML5: "devicon-html5-plain colored",
  CSS3: "devicon-css3-plain colored",
  Sass: "devicon-sass-plain colored",
  "Vue.js": "devicon-vuejs-plain colored",
  Gatsby: "devicon-gatsby-plain colored",
  "Tailwind CSS": "devicon-tailwindcss-plain colored",
  "Node.js": "devicon-nodejs-plain colored",
  Mocha: "devicon-mocha-plain colored",
  MongoDB: "devicon-mongodb-plain colored",
  Elasticsearch: "devicon-elasticsearch-plain colored",
  Express: "devicon-express-original",
  Git: "devicon-git-plain colored",
  GitHub: "devicon-github-original",
  ESLint: "devicon-eslint-plain colored",
  Vite: "devicon-vite-plain colored",
  webpack: "devicon-webpack-plain colored",
  Docker: "devicon-docker-plain colored",
  Jenkins: "devicon-jenkins-plain colored",
  Kubernetes: "devicon-kubernetes-plain colored",
  "GitHub Actions": "devicon-githubactions-plain colored",
  "D3.js": "devicon-d3js-plain colored",
  Pandas: "devicon-pandas-plain",
  NumPy: "devicon-numpy-plain colored",
  "Arch Linux": "devicon-archlinux-plain colored",
  Vim: "devicon-vim-plain colored",
  Neovim: "devicon-neovim-plain colored",
  PNPM: "devicon-pnpm-plain colored",
  Homebrew: "devicon-homebrew-plain colored",
};
